services:
  direct:
    command: python3 /src/rtllm_cvdp_harness.py
    env_file: ./src/.env
    image: portle-oss-cad-suite:latest
    volumes:
    - ./src/:/src/
    - ./rtl/:/rtl/
    working_dir: /code/rundir
